### ISSUE TITLE
Ignore Pinned Tabs

### ISSUE THREAD

**Issue by WHiZSTA** [mattorchard/grouper#4]
Forgot to ask, can you please have it ignore pinned tabs in the sort? When a pinned tab gets matched by a rule it removes the pin status to put it in a group.

**Comment by mattorchard** [comment]
Ooh, glad you asked for this, version `v0.1.0` (and potentially earlier versions) don't sort correctly if you have any pinned tabs.
Should be fixed in `v0.1.1` (and also pinned tabs won't be included in the groupings)
