### ISSUE TITLE
Sort With-in Groups - Enhancement

### ISSUE THREAD

**Issue by WHiZSTA** [mattorchard/grouper#5]
An idea i haven't seen implemented in any of the other tab group plugins is sorting with-in the actual groups. It's actually super handy and i think you might like the result, but the only way to currently do it in any of them is to de-group, and use a simple tab sorter to sort by domain, then re-group and everything should be in a nice order within the group by domain. 

I'm not sure if you'd consider something like this useful or not as an option, but i thought i'd suggest it while you are already looking at where to assign tabs to, incase it's an idea you like. Below is a screenshot of the resulting order, as you can see it makes having the groups by general topic more useful as when you go into it, sort of hybrid-like between topic groups+domain groups, as you can then drill down to the specific sites you wanted easier than just a chaotic order.

![image](https://github.com/mattorchard/grouper/assets/18521070/928ffabf-906a-48d3-9d08-ac64a82bf27b)

**Comment by mattorchard** [comment]
I think this feature is a little too costly in the effort-to-reward ratio.

The Chrome APIs for updating tab positions require setting each tab's individual index, so they are pretty annoying to work with.
I could also imagine they would not be great for performance as each tab would have to ensure the others had finished moving before moving the next, and reordering the groups would cause lots of move-checks.

Also personally, I like keeping the tabs in a manual order within the groups, so this would need an option for toggling between `no sort`, `URL sort`, or `tab title sort` which also adds complexity.

For what it's worth: I think most users can _kind of_ work around not having this by using `auto-group` and `alphabetical sort`.
Obviously that creates more groups in cases where the user has a lot of different sites open, but in the average case I think it works pretty well.
